[build]
  functions = "netlify/functions"

# Esto redirige tus peticiones limpias a la funci√≥n oculta
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy?endpoint=:splat"
  status = 200